
<div class="panel panel-primary">
	<div class="panel-heading"> Data Konken</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-striped table-hover ">
				<thead>
					<tr>
						<th>idstatuskend</th>
						<th>idkendaraan</th>
						<th>supir</th>
						<th>tglterima</th>
						<th>kondisi</th>
						<th>ada1</th>
						<th>ada2</th>
						<th>ada3</th>
						<th>ada4</th>
						<th>ada5</th>
						<th>ada6</th>
						<th>ada7</th>
						<th>ada8</th>
						<th>ada9</th>
						<th>ada10</th>
						<th>ada11</th>
						<th>ada12</th>
						<th>ada13</th>
						<th>ada14</th>
						<th>ada15</th>
						<th>ada16</th>
						<th>ada17</th>
						<th>ada18</th>
						<th>ada19</th>
						<th>ada20</th>
						<th>ada21</th>
						<th>ada22</th>
						<th>ada23</th>
						<th>ada24</th>
						<th>ada25</th>
						<th>ada26</th>
						<th>ada27</th>
						<th>ada28</th>
						<th>ada29</th>
						<th>ada30</th>
						<th>ada31</th>
						<th>ada32</th>
						<th>ada33</th>
						<th>ada34</th>
						<th>ada35</th>
						<th>ada36</th>
						<th>ada37</th>
						<th>ada38</th>
						<th>ada39</th>
						<th>ada40</th>
						<th>ada41</th>
						<th>ada42</th>
						<th>ada43</th>
						<th>ada44</th>
						<th>ada45</th>
						<th>ada46</th>
						<th>ada47</th>
						<th>ada48</th>
						<th>ada49</th>
						<th>ada50</th>
						<th>ada51</th>
						<th>ada52</th>
						<th>ada53</th>
						<th>ada54</th>
						<th>ada55</th>
						<th>ada56</th>
						<th>ada57</th>
						<th>ada58</th>
						<th>ada59</th>
						<th>ada60</th>
						<th>ada61</th>
						<th>ada62</th>
						<th>ada63</th>
						<th>ada64</th>
						<th>barang1</th>
						<th>barang2</th>
						<th>barang3</th>
						<th>barang4</th>
						<th>barang5</th>
						<th>barang6</th>
						<th>barang7</th>
						<th>barang8</th>
						<th>barang9</th>
						<th>barang10</th>
						<th>barang11</th>
						<th>barang12</th>
						<th>barang13</th>
						<th>barang14</th>
						<th>barang15</th>
						<th>barang16</th>
						<th>barang17</th>
						<th>barang18</th>
						<th>barang19</th>
						<th>barang20</th>
						<th>barang21</th>
						<th>barang22</th>
						<th>barang23</th>
						<th>barang24</th>
						<th>barang25</th>
						<th>barang26</th>
						<th>barang27</th>
						<th>barang28</th>
						<th>barang29</th>
						<th>barang30</th>
						<th>barang31</th>
						<th>barang32</th>
						<th>barang33</th>
						<th>barang34</th>
						<th>barang35</th>
						<th>barang36</th>
						<th>barang37</th>
						<th>barang38</th>
						<th>barang39</th>
						<th>barang40</th>
						<th>barang41</th>
						<th>barang42</th>
						<th>barang43</th>
						<th>barang44</th>
						<th>barang45</th>
						<th>barang46</th>
						<th>barang47</th>
						<th>barang48</th>
						<th>barang49</th>
						<th>barang50</th>
						<th>barang51</th>
						<th>barang52</th>
						<th>barang53</th>
						<th>barang54</th>
						<th>barang55</th>
						<th>barang56</th>
						<th>barang57</th>
						<th>barang58</th>
						<th>barang59</th>
						<th>barang60</th>
						<th>barang61</th>
						<th>barang62</th>
						<th>barang63</th>
						<th>barang64</th>
						<th>insertedby</th>
						<th>inserteddate</th>
						<th>updatedby</th>
						<th>updateddate</th>
						<th><?php echo anchor('konken/konken_form_insert/', '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>')?></th>
					</tr>
				</thead>
				<tbody>
					<?php
					$i=1;
					foreach($konken_list as $row): 
						?>
						<tr>
							<td><?=$row['idstatuskend']?></td>
							<td><?=$row['idkendaraan']?></td>
							<td><?=$row['supir']?></td>
							<td><?=$row['tglterima']?></td>
							<td><?=$row['kondisi']?></td>
							<td><?=$row['ada1']?></td>
							<td><?=$row['ada2']?></td>
							<td><?=$row['ada3']?></td>
							<td><?=$row['ada4']?></td>
							<td><?=$row['ada5']?></td>
							<td><?=$row['ada6']?></td>
							<td><?=$row['ada7']?></td>
							<td><?=$row['ada8']?></td>
							<td><?=$row['ada9']?></td>
							<td><?=$row['ada10']?></td>
							<td><?=$row['ada11']?></td>
							<td><?=$row['ada12']?></td>
							<td><?=$row['ada13']?></td>
							<td><?=$row['ada14']?></td>
							<td><?=$row['ada15']?></td>
							<td><?=$row['ada16']?></td>
							<td><?=$row['ada17']?></td>
							<td><?=$row['ada18']?></td>
							<td><?=$row['ada19']?></td>
							<td><?=$row['ada20']?></td>
							<td><?=$row['ada21']?></td>
							<td><?=$row['ada22']?></td>
							<td><?=$row['ada23']?></td>
							<td><?=$row['ada24']?></td>
							<td><?=$row['ada25']?></td>
							<td><?=$row['ada26']?></td>
							<td><?=$row['ada27']?></td>
							<td><?=$row['ada28']?></td>
							<td><?=$row['ada29']?></td>
							<td><?=$row['ada30']?></td>
							<td><?=$row['ada31']?></td>
							<td><?=$row['ada32']?></td>
							<td><?=$row['ada33']?></td>
							<td><?=$row['ada34']?></td>
							<td><?=$row['ada35']?></td>
							<td><?=$row['ada36']?></td>
							<td><?=$row['ada37']?></td>
							<td><?=$row['ada38']?></td>
							<td><?=$row['ada39']?></td>
							<td><?=$row['ada40']?></td>
							<td><?=$row['ada41']?></td>
							<td><?=$row['ada42']?></td>
							<td><?=$row['ada43']?></td>
							<td><?=$row['ada44']?></td>
							<td><?=$row['ada45']?></td>
							<td><?=$row['ada46']?></td>
							<td><?=$row['ada47']?></td>
							<td><?=$row['ada48']?></td>
							<td><?=$row['ada49']?></td>
							<td><?=$row['ada50']?></td>
							<td><?=$row['ada51']?></td>
							<td><?=$row['ada52']?></td>
							<td><?=$row['ada53']?></td>
							<td><?=$row['ada54']?></td>
							<td><?=$row['ada55']?></td>
							<td><?=$row['ada56']?></td>
							<td><?=$row['ada57']?></td>
							<td><?=$row['ada58']?></td>
							<td><?=$row['ada59']?></td>
							<td><?=$row['ada60']?></td>
							<td><?=$row['ada61']?></td>
							<td><?=$row['ada62']?></td>
							<td><?=$row['ada63']?></td>
							<td><?=$row['ada64']?></td>
							<td><?=$row['barang1']?></td>
							<td><?=$row['barang2']?></td>
							<td><?=$row['barang3']?></td>
							<td><?=$row['barang4']?></td>
							<td><?=$row['barang5']?></td>
							<td><?=$row['barang6']?></td>
							<td><?=$row['barang7']?></td>
							<td><?=$row['barang8']?></td>
							<td><?=$row['barang9']?></td>
							<td><?=$row['barang10']?></td>
							<td><?=$row['barang11']?></td>
							<td><?=$row['barang12']?></td>
							<td><?=$row['barang13']?></td>
							<td><?=$row['barang14']?></td>
							<td><?=$row['barang15']?></td>
							<td><?=$row['barang16']?></td>
							<td><?=$row['barang17']?></td>
							<td><?=$row['barang18']?></td>
							<td><?=$row['barang19']?></td>
							<td><?=$row['barang20']?></td>
							<td><?=$row['barang21']?></td>
							<td><?=$row['barang22']?></td>
							<td><?=$row['barang23']?></td>
							<td><?=$row['barang24']?></td>
							<td><?=$row['barang25']?></td>
							<td><?=$row['barang26']?></td>
							<td><?=$row['barang27']?></td>
							<td><?=$row['barang28']?></td>
							<td><?=$row['barang29']?></td>
							<td><?=$row['barang30']?></td>
							<td><?=$row['barang31']?></td>
							<td><?=$row['barang32']?></td>
							<td><?=$row['barang33']?></td>
							<td><?=$row['barang34']?></td>
							<td><?=$row['barang35']?></td>
							<td><?=$row['barang36']?></td>
							<td><?=$row['barang37']?></td>
							<td><?=$row['barang38']?></td>
							<td><?=$row['barang39']?></td>
							<td><?=$row['barang40']?></td>
							<td><?=$row['barang41']?></td>
							<td><?=$row['barang42']?></td>
							<td><?=$row['barang43']?></td>
							<td><?=$row['barang44']?></td>
							<td><?=$row['barang45']?></td>
							<td><?=$row['barang46']?></td>
							<td><?=$row['barang47']?></td>
							<td><?=$row['barang48']?></td>
							<td><?=$row['barang49']?></td>
							<td><?=$row['barang50']?></td>
							<td><?=$row['barang51']?></td>
							<td><?=$row['barang52']?></td>
							<td><?=$row['barang53']?></td>
							<td><?=$row['barang54']?></td>
							<td><?=$row['barang55']?></td>
							<td><?=$row['barang56']?></td>
							<td><?=$row['barang57']?></td>
							<td><?=$row['barang58']?></td>
							<td><?=$row['barang59']?></td>
							<td><?=$row['barang60']?></td>
							<td><?=$row['barang61']?></td>
							<td><?=$row['barang62']?></td>
							<td><?=$row['barang63']?></td>
							<td><?=$row['barang64']?></td>
							<td><?=$row['insertedby']?></td>
							<td><?=$row['inserteddate']?></td>
							<td><?=$row['updatedby']?></td>
							<td><?=$row['updateddate']?></td>
							<td align="center">
								<?php echo anchor('konken/konken_form_update/'.$row['idstatuskend'], '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>')?>
								<?php echo anchor('konken/konken_form_delete/'.$row['idstatuskend'], '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>')?>
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</div>

