
<div class="panel panel-primary">
	<div class="panel-heading"> Data Konken</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-striped table-hover ">
				<thead>
					<tr>
						<th>idstatuskend</th>
						<th>idkendaraan</th>
						<th>supir</th>
						<th>tglterima</th>
						<th>kondisi</th>
						<th>barang1</th>
						<th>barang2</th>
						<th>barang3</th>
						<th>barang4</th>
						<th>barang5</th>
						<th>barang6</th>
						<th>barang7</th>
						<th>barang8</th>
						<th>barang9</th>
						<th>barang10</th>
						<th>barang11</th>
						<th>barang12</th>
						<th>barang13</th>
						<th>barang14</th>
						<th>barang15</th>
						<th>barang16</th>
						<th>barang17</th>
						<th>barang18</th>
						<th>barang19</th>
						<th>barang20</th>
						<th>barang21</th>
						<th>barang22</th>
						<th>barang23</th>
						<th>barang24</th>
						<th>barang25</th>
						<th>barang26</th>
						<th>barang27</th>
						<th>barang28</th>
						<th>barang29</th>
						<th>barang30</th>
						<th>barang31</th>
						<th>barang32</th>
						<th>barang33</th>
						<th>barang34</th>
						<th>barang35</th>
						<th>barang36</th>
						<th>barang37</th>
						<th>barang38</th>
						<th>barang39</th>
						<th>barang40</th>
						<th>barang41</th>
						<th>barang42</th>
						<th>barang43</th>
						<th>barang44</th>
						<th>barang45</th>
						<th>barang46</th>
						<th>barang47</th>
						<th>barang48</th>
						<th>barang49</th>
						<th>barang50</th>
						<th>barang51</th>
						<th>barang52</th>
						<th>barang53</th>
						<th>barang54</th>
						<th>barang55</th>
						<th>barang56</th>
						<th>barang57</th>
						<th>barang58</th>
						<th>barang59</th>
						<th>barang60</th>
						<th>barang61</th>
						<th>barang62</th>
						<th>barang63</th>
						<th>barang64</th>
						<th>insertedby</th>
						<th>inserteddate</th>
						<th>updatedby</th>
						<th>updateddate</th>
						<th><?php echo anchor('konken/konken_form_insert/', '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>')?></th>
					</tr>
				</thead>
				<tbody>
					<?php
					$i=1;
					foreach($konken_list as $row): 
						?>
						<tr>
							<td><?=$row['idstatuskend']?></td>
							<td><?=$row['idkendaraan']?></td>
							<td><?=$row['supir']?></td>
							<td><?=$row['tglterima']?></td>
							<td><?=$row['kondisi']?></td>
							<td><?=$row['barang1']?></td>
							<td><?=$row['barang2']?></td>
							<td><?=$row['barang3']?></td>
							<td><?=$row['barang4']?></td>
							<td><?=$row['barang5']?></td>
							<td><?=$row['barang6']?></td>
							<td><?=$row['barang7']?></td>
							<td><?=$row['barang8']?></td>
							<td><?=$row['barang9']?></td>
							<td><?=$row['barang10']?></td>
							<td><?=$row['barang11']?></td>
							<td><?=$row['barang12']?></td>
							<td><?=$row['barang13']?></td>
							<td><?=$row['barang14']?></td>
							<td><?=$row['barang15']?></td>
							<td><?=$row['barang16']?></td>
							<td><?=$row['barang17']?></td>
							<td><?=$row['barang18']?></td>
							<td><?=$row['barang19']?></td>
							<td><?=$row['barang20']?></td>
							<td><?=$row['barang21']?></td>
							<td><?=$row['barang22']?></td>
							<td><?=$row['barang23']?></td>
							<td><?=$row['barang24']?></td>
							<td><?=$row['barang25']?></td>
							<td><?=$row['barang26']?></td>
							<td><?=$row['barang27']?></td>
							<td><?=$row['barang28']?></td>
							<td><?=$row['barang29']?></td>
							<td><?=$row['barang30']?></td>
							<td><?=$row['barang31']?></td>
							<td><?=$row['barang32']?></td>
							<td><?=$row['barang33']?></td>
							<td><?=$row['barang34']?></td>
							<td><?=$row['barang35']?></td>
							<td><?=$row['barang36']?></td>
							<td><?=$row['barang37']?></td>
							<td><?=$row['barang38']?></td>
							<td><?=$row['barang39']?></td>
							<td><?=$row['barang40']?></td>
							<td><?=$row['barang41']?></td>
							<td><?=$row['barang42']?></td>
							<td><?=$row['barang43']?></td>
							<td><?=$row['barang44']?></td>
							<td><?=$row['barang45']?></td>
							<td><?=$row['barang46']?></td>
							<td><?=$row['barang47']?></td>
							<td><?=$row['barang48']?></td>
							<td><?=$row['barang49']?></td>
							<td><?=$row['barang50']?></td>
							<td><?=$row['barang51']?></td>
							<td><?=$row['barang52']?></td>
							<td><?=$row['barang53']?></td>
							<td><?=$row['barang54']?></td>
							<td><?=$row['barang55']?></td>
							<td><?=$row['barang56']?></td>
							<td><?=$row['barang57']?></td>
							<td><?=$row['barang58']?></td>
							<td><?=$row['barang59']?></td>
							<td><?=$row['barang60']?></td>
							<td><?=$row['barang61']?></td>
							<td><?=$row['barang62']?></td>
							<td><?=$row['barang63']?></td>
							<td><?=$row['barang64']?></td>
							<td><?=$row['insertedby']?></td>
							<td><?=$row['inserteddate']?></td>
							<td><?=$row['updatedby']?></td>
							<td><?=$row['updateddate']?></td>
							<td align="center">
								<?php echo anchor('konken/konken_form_update/'.$row['idstatuskend'], '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>')?>
								<?php echo anchor('konken/konken_form_delete/'.$row['idstatuskend'], '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>')?>
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</div>

